### ISSUE TITLE
Falha ao tentar inicializar o bot

### ISSUE THREAD

**Issue by Amovoce1** [Niruon/Nourin#1]
Seria possível um tutorial de instalação mais completo?
No meu está dando um erro na hora de executar dizendo que não tenho autorização de utilizar o token.
Obrigada dês de ja

**Comment by Niruon** [comment]
Como foi deixado claro na nossa conversa através do Telegram, o erro não estava relacionado ao bot em sí, mas sim, a uma limitação do ambiente de operações no qual você estava tentando executá-lo.

Como o problema foi resolvido, estarei fechando essa issue agora.
