### ISSUE TITLE
Após a execução do código, não há qualquer resposta do bot

### ISSUE THREAD

**Issue by ElissonRodrigues** [Niruon/Nourin#2]
![Screenshot_20200319-213025_Plus](https://user-images.githubusercontent.com/25101186/77126722-e287ad00-6a28-11ea-87c0-7e47da576864.jpg)

Fiz a tudo conforme indicado, apesar disso não há qualquer resposta

**Comment by ElissonRodrigues** [comment]
![20200319_212928](https://user-images.githubusercontent.com/25101186/77126864-4ca05200-6a29-11ea-94c7-26cdc7f75910.jpg)

**Comment by Niruon** [comment]
Problema resolvido no commit [3c1c6a9](https://github.com/Niruon/Nourin/commit/3c1c6a94a5316ca2d75d93ed2540c2f60573b852).
